/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author aluno
 */
public class telaCalculadora extends javax.swing.JFrame {
double valor1, valor2, resultado, m;
int operacao, op;
boolean tela;
String visor;

    /**
     * Creates new form telaCalculadora
     */
    public telaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bMr = new javax.swing.JButton();
        bApagar = new javax.swing.JButton();
        bSete = new javax.swing.JButton();
        bQuatro = new javax.swing.JButton();
        bZero = new javax.swing.JButton();
        bUm = new javax.swing.JButton();
        bMais = new javax.swing.JButton();
        bMenos = new javax.swing.JButton();
        bVezes = new javax.swing.JButton();
        bDivisao = new javax.swing.JButton();
        bMaiseMenos = new javax.swing.JButton();
        bMmais = new javax.swing.JButton();
        bMmenos = new javax.swing.JButton();
        bPorcentagem = new javax.swing.JButton();
        bIgual = new javax.swing.JButton();
        bRaizQuadrada = new javax.swing.JButton();
        bOito = new javax.swing.JButton();
        bDois = new javax.swing.JButton();
        bApagarTudo = new javax.swing.JButton();
        bCinco = new javax.swing.JButton();
        bNove = new javax.swing.JButton();
        bVirgula = new javax.swing.JButton();
        bTres = new javax.swing.JButton();
        bSeis = new javax.swing.JButton();
        tfTela = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bMr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bMr.setText("MR");
        bMr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMrActionPerformed(evt);
            }
        });

        bApagar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bApagar.setText("<--");
        bApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApagarActionPerformed(evt);
            }
        });

        bSete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bSete.setText("7");
        bSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeteActionPerformed(evt);
            }
        });

        bQuatro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bQuatro.setText("4");
        bQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuatroActionPerformed(evt);
            }
        });

        bZero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bZero.setText("0");
        bZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZeroActionPerformed(evt);
            }
        });

        bUm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bUm.setText("1");
        bUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUmActionPerformed(evt);
            }
        });

        bMais.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bMais.setText("+");
        bMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMaisActionPerformed(evt);
            }
        });

        bMenos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bMenos.setText("-");
        bMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenosActionPerformed(evt);
            }
        });

        bVezes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bVezes.setText("*");
        bVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVezesActionPerformed(evt);
            }
        });

        bDivisao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bDivisao.setText("/");
        bDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivisaoActionPerformed(evt);
            }
        });

        bMaiseMenos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bMaiseMenos.setText("+-");
        bMaiseMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMaiseMenosActionPerformed(evt);
            }
        });

        bMmais.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bMmais.setText("M+");
        bMmais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMmaisActionPerformed(evt);
            }
        });

        bMmenos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bMmenos.setText("M-");
        bMmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMmenosActionPerformed(evt);
            }
        });

        bPorcentagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bPorcentagem.setText("%");
        bPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPorcentagemActionPerformed(evt);
            }
        });

        bIgual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bIgual.setText("=");
        bIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIgualActionPerformed(evt);
            }
        });

        bRaizQuadrada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bRaizQuadrada.setText("SQ");
        bRaizQuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRaizQuadradaActionPerformed(evt);
            }
        });

        bOito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bOito.setText("8");
        bOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOitoActionPerformed(evt);
            }
        });

        bDois.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bDois.setText("2");
        bDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDoisActionPerformed(evt);
            }
        });

        bApagarTudo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bApagarTudo.setText("CE");
        bApagarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApagarTudoActionPerformed(evt);
            }
        });

        bCinco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bCinco.setText("5");
        bCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCincoActionPerformed(evt);
            }
        });

        bNove.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bNove.setText("9");
        bNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNoveActionPerformed(evt);
            }
        });

        bVirgula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bVirgula.setText(",");
        bVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVirgulaActionPerformed(evt);
            }
        });

        bTres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bTres.setText("3");
        bTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTresActionPerformed(evt);
            }
        });

        bSeis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bSeis.setText("6");
        bSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeisActionPerformed(evt);
            }
        });

        tfTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bZero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bSete)
                                    .addComponent(bQuatro)
                                    .addComponent(bUm))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(bOito))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bDois))))
                            .addComponent(bCinco, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bSeis)
                                        .addGap(18, 18, 18)
                                        .addComponent(bVezes))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bTres)
                                        .addGap(18, 18, 18)
                                        .addComponent(bMenos))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bVirgula)
                                        .addGap(18, 18, 18)
                                        .addComponent(bMais)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bIgual))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bNove)
                                .addGap(18, 18, 18)
                                .addComponent(bDivisao)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTela, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bMr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bMmais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bMmenos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bRaizQuadrada))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bApagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bApagarTudo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bMaiseMenos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bPorcentagem)))
                        .addGap(2, 2, 2)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tfTela, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bApagarTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bMaiseMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bMmais, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bMr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bMmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bRaizQuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bNove, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bOito, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bUm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bDois, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bTres, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bZero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bMais, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("   ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMrActionPerformed
        if(m!=0){
            tfTela.setText(String.valueOf(m));
        }
    }//GEN-LAST:event_bMrActionPerformed

    private void bApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApagarActionPerformed
        visor=tfTela.getText();
        
        if(!"".equals(visor)){
            String diminuir = visor.substring(0, visor.length()-1);
            tfTela.setText(""+diminuir);
        }
    }//GEN-LAST:event_bApagarActionPerformed

    private void bSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeteActionPerformed
          if(tela==false){
         tfTela.setText(tfTela.getText()+"7");
     }else{
         tfTela.setText("7");
         tela=false;
     }
      
    }//GEN-LAST:event_bSeteActionPerformed

    private void bQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuatroActionPerformed
        if(tela==false){
         tfTela.setText(tfTela.getText()+"4");
     }else{
         tfTela.setText("4");
         tela=false;
     }
      
    }//GEN-LAST:event_bQuatroActionPerformed

    private void bZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZeroActionPerformed
         if(tela==false){
         tfTela.setText(tfTela.getText()+"0");
     }else{
         tfTela.setText("0");
         tela=false;
     }
      
    }//GEN-LAST:event_bZeroActionPerformed

    private void bUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUmActionPerformed
       if(tela==false){
         tfTela.setText(tfTela.getText()+"1");
     }else{
         tfTela.setText("1");
         tela=false;
     }
      
    }//GEN-LAST:event_bUmActionPerformed

    private void bMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMaisActionPerformed
     
        if(operacao == 0){
         valor1 =  Double.parseDouble(tfTela.getText());
          tfTela.setText("");
          operacao=1;   
        }else if(operacao == 1){
            valor2=Double.parseDouble(tfTela.getText());
            valor1+=valor2;
        }else if(operacao == 2){
            valor2=Double.parseDouble(tfTela.getText());
            valor1-=valor2;
        }else if(operacao == 3){
            valor2=Double.parseDouble(tfTela.getText());
            valor1*=valor2;
        }else if(operacao == 4){
            valor2=Double.parseDouble(tfTela.getText());
            valor1/=valor2;
        }
        tfTela.setText(""+valor1);
        tela=true;
        operacao = 1;
        
        
        
        
      
    }//GEN-LAST:event_bMaisActionPerformed

    private void bMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenosActionPerformed
   
              if(operacao == 0){
         valor1 =  Double.parseDouble(tfTela.getText());
          tfTela.setText("");
          operacao=2;   
        }else if(operacao == 1){
            valor2=Double.parseDouble(tfTela.getText());
            valor1+=valor2;
        }else if(operacao == 2){
            valor2=Double.parseDouble(tfTela.getText());
            valor1-=valor2;
        }else if(operacao == 3){
            valor2=Double.parseDouble(tfTela.getText());
            valor1*=valor2;
        }else if(operacao == 4){
            valor2=Double.parseDouble(tfTela.getText());
            valor1/=valor2;
        }
        tfTela.setText(""+valor1);
        tela=true;
        operacao = 2;
        
      
    }//GEN-LAST:event_bMenosActionPerformed

    private void bVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVezesActionPerformed
        if(operacao == 0){
         valor1 =  Double.parseDouble(tfTela.getText());
          tfTela.setText("");
          operacao=3;   
        }else if(operacao == 1){
            valor2=Double.parseDouble(tfTela.getText());
            valor1+=valor2;
        }else if(operacao == 2){
            valor2=Double.parseDouble(tfTela.getText());
            valor1-=valor2;
        }else if(operacao == 3){
            valor2=Double.parseDouble(tfTela.getText());
            valor1*=valor2;
        }else if(operacao == 4){
            valor2=Double.parseDouble(tfTela.getText());
            valor1/=valor2;
        }
        tfTela.setText(""+valor1);
        tela=true;
        operacao = 3;
    }//GEN-LAST:event_bVezesActionPerformed

    private void bDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivisaoActionPerformed
             if(operacao == 0){
         valor1 =  Double.parseDouble(tfTela.getText());
          tfTela.setText("");
          operacao=4;   
        }else if(operacao == 1){
            valor2=Double.parseDouble(tfTela.getText());
            valor1+=valor2;
        }else if(operacao == 2){
            valor2=Double.parseDouble(tfTela.getText());
            valor1-=valor2;
        }else if(operacao == 3){
            valor2=Double.parseDouble(tfTela.getText());
            valor1*=valor2;
        }else if(operacao == 4){
            valor2=Double.parseDouble(tfTela.getText());
            valor1/=valor2;
        }
        tfTela.setText(""+valor1);
        tela=true;
        operacao = 4;
    }//GEN-LAST:event_bDivisaoActionPerformed

    private void bMaiseMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMaiseMenosActionPerformed
       visor= tfTela.getText();
       if(!"".equals(visor)){
           String inverterSinal = visor.substring(0,1);
           
           if("-".equals(inverterSinal)){
               inverterSinal=
                       visor.substring(1,visor.length());
               tfTela.setText(""+inverterSinal);
           }else{
               tfTela.setText("-"+visor);
           }
       }
    }//GEN-LAST:event_bMaiseMenosActionPerformed

    private void bMmaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMmaisActionPerformed
        m =  Double.parseDouble(tfTela.getText());
    }//GEN-LAST:event_bMmaisActionPerformed

    private void bMmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMmenosActionPerformed
        m=0;
    }//GEN-LAST:event_bMmenosActionPerformed

    private void bPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPorcentagemActionPerformed
        valor2=Double.parseDouble(tfTela.getText());
        if(operacao == 1){
           resultado=valor1+(valor1*valor2)/100;
       } else if(operacao == 2){
          resultado=valor1-(valor1*valor2/100);
       }else if(operacao == 3){
           resultado=(valor1*valor2)/100;
       }
        tfTela.setText(""+resultado);
       tela = true;
    }//GEN-LAST:event_bPorcentagemActionPerformed

    private void bIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIgualActionPerformed
valor2=Double.parseDouble(tfTela.getText());       
       
       if(operacao==1){
           resultado=valor1+valor2;
       } else if(operacao ==2){
           resultado=valor1-valor2;
       }else if(operacao == 3){
           resultado=valor1*valor2;
       }else if(operacao == 4){
           resultado=valor1/valor2;
       }
       tfTela.setText(""+resultado);
       tela = true;
    }//GEN-LAST:event_bIgualActionPerformed

    private void bRaizQuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRaizQuadradaActionPerformed
    valor1=Double.parseDouble(tfTela.getText());
        Math.sqrt(valor1);
        tfTela.setText(String.valueOf(Math.sqrt(valor1)));
    }//GEN-LAST:event_bRaizQuadradaActionPerformed

    private void bOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOitoActionPerformed
     if(tela==false){
         tfTela.setText(tfTela.getText()+"8");
     }else{
         tfTela.setText("8");
         tela=false;
     }
      
    }//GEN-LAST:event_bOitoActionPerformed

    private void bDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDoisActionPerformed
         if(tela==false){
         tfTela.setText(tfTela.getText()+"2");
     }else{
         tfTela.setText("2");
         tela=false;
     }
      
    }//GEN-LAST:event_bDoisActionPerformed

    private void bApagarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApagarTudoActionPerformed
        tfTela.setText("");
    }//GEN-LAST:event_bApagarTudoActionPerformed

    private void bCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCincoActionPerformed
         if(tela==false){
         tfTela.setText(tfTela.getText()+"5");
     }else{
         tfTela.setText("5");
         tela=false;
     }
      
    }//GEN-LAST:event_bCincoActionPerformed

    private void bNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNoveActionPerformed
     if(tela==false){
         tfTela.setText(tfTela.getText()+"9");
     }else{
         tfTela.setText("9");
         tela=false;
     }
      
    }//GEN-LAST:event_bNoveActionPerformed

    private void bVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVirgulaActionPerformed
       tfTela.setText(tfTela.getText()+".");
    }//GEN-LAST:event_bVirgulaActionPerformed

    private void bTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTresActionPerformed
          if(tela==false){
         tfTela.setText(tfTela.getText()+"3");
     }else{
         tfTela.setText("3");
         tela=false;
     }
      
    }//GEN-LAST:event_bTresActionPerformed

    private void bSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeisActionPerformed
     if(tela==false){
         tfTela.setText(tfTela.getText()+"6");
     }else{
         tfTela.setText("6");
         tela=false;
     }
      
    }//GEN-LAST:event_bSeisActionPerformed

    private void tfTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelaActionPerformed
    // System.out.println();
    }//GEN-LAST:event_tfTelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCalculadora().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bApagar;
    private javax.swing.JButton bApagarTudo;
    private javax.swing.JButton bCinco;
    private javax.swing.JButton bDivisao;
    private javax.swing.JButton bDois;
    private javax.swing.JButton bIgual;
    private javax.swing.JButton bMais;
    private javax.swing.JButton bMaiseMenos;
    private javax.swing.JButton bMenos;
    private javax.swing.JButton bMmais;
    private javax.swing.JButton bMmenos;
    private javax.swing.JButton bMr;
    private javax.swing.JButton bNove;
    private javax.swing.JButton bOito;
    private javax.swing.JButton bPorcentagem;
    private javax.swing.JButton bQuatro;
    private javax.swing.JButton bRaizQuadrada;
    private javax.swing.JButton bSeis;
    private javax.swing.JButton bSete;
    private javax.swing.JButton bTres;
    private javax.swing.JButton bUm;
    private javax.swing.JButton bVezes;
    private javax.swing.JButton bVirgula;
    private javax.swing.JButton bZero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfTela;
    // End of variables declaration//GEN-END:variables
}
